#!/usr/bin/env python3
"""Generate the analytical target and C headers for the relaxation benchmark.

This wrapper deliberately reuses the uploaded solver's maintained base-state
formulation.  It adds only benchmark-specific inputs and convenient two-column
reference files for the runtime comparison.
"""

from __future__ import annotations

import argparse
import configparser
import hashlib
import math
import shutil
from pathlib import Path

import numpy as np

import generate_dimensionless_base_state as base_generator


def required_float(parser: configparser.ConfigParser, section: str, name: str) -> float:
    try:
        value = parser.getfloat(section, name)
    except (configparser.Error, ValueError) as exc:
        raise ValueError(f"Missing or invalid [{section}] {name}") from exc
    if not math.isfinite(value):
        raise ValueError(f"[{section}] {name} must be finite")
    return value


def required_int(parser: configparser.ConfigParser, section: str, name: str) -> int:
    try:
        return parser.getint(section, name)
    except (configparser.Error, ValueError) as exc:
        raise ValueError(f"Missing or invalid [{section}] {name}") from exc


def required_bool(parser: configparser.ConfigParser, section: str, name: str) -> bool:
    try:
        return parser.getboolean(section, name)
    except (configparser.Error, ValueError) as exc:
        raise ValueError(f"Missing or invalid [{section}] {name}") from exc


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def write_two_column(path: Path, z: np.ndarray, values: np.ndarray, name: str) -> None:
    with path.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by generate_steady_uniform_case.py\n")
        stream.write(f"# columns: z_star    {name}_star\n")
        for zz, value in zip(z, values):
            stream.write(f"{zz:.16e}\t{value:.16e}\n")


def parse_benchmark_settings(config_path: Path) -> dict[str, float | int | bool]:
    parser = configparser.ConfigParser(inline_comment_prefixes=("#", ";"))
    if not parser.read(config_path):
        raise FileNotFoundError(config_path)

    values: dict[str, float | int | bool] = {
        "initial_uniform_velocity": required_float(
            parser, "steady_uniform", "initial_uniform_velocity"
        ),
        "comparison_output_dt": required_float(
            parser, "steady_uniform", "comparison_output_dt"
        ),
        "stop_when_converged": required_bool(
            parser, "steady_uniform", "stop_when_converged"
        ),
        "convergence_relative_rms": required_float(
            parser, "steady_uniform", "convergence_relative_rms"
        ),
        "convergence_hold_outputs": required_int(
            parser, "steady_uniform", "convergence_hold_outputs"
        ),
    }

    if not (0.0 <= values["initial_uniform_velocity"] < 1.0):
        raise ValueError(
            "[steady_uniform] initial_uniform_velocity must lie in [0,1) "
            "because U_l=1 is the target lower-layer mean"
        )
    if values["comparison_output_dt"] <= 0.0:
        raise ValueError("comparison_output_dt must be positive")
    if values["convergence_relative_rms"] <= 0.0:
        raise ValueError("convergence_relative_rms must be positive")
    if values["convergence_hold_outputs"] <= 0:
        raise ValueError("convergence_hold_outputs must be positive")
    return values


def write_benchmark_header(path: Path, settings: dict[str, float | int | bool]) -> None:
    with path.open("w", encoding="utf-8") as stream:
        stream.write("/* Generated benchmark controls. Edit the INI, not this file. */\n")
        stream.write("#ifndef BASILISK_STEADY_UNIFORM_GENERATED_H\n")
        stream.write("#define BASILISK_STEADY_UNIFORM_GENERATED_H\n\n")
        stream.write(
            "#define CASE_INITIAL_UNIFORM_VELOCITY "
            f"{float(settings['initial_uniform_velocity']):.17e}\n"
        )
        stream.write(
            "#define CASE_COMPARISON_OUTPUT_DT "
            f"{float(settings['comparison_output_dt']):.17e}\n"
        )
        stream.write(
            "#define CASE_STOP_WHEN_CONVERGED "
            f"{1 if settings['stop_when_converged'] else 0}\n"
        )
        stream.write(
            "#define CASE_CONVERGENCE_RELATIVE_RMS "
            f"{float(settings['convergence_relative_rms']):.17e}\n"
        )
        stream.write(
            "#define CASE_CONVERGENCE_HOLD_OUTPUTS "
            f"{int(settings['convergence_hold_outputs'])}\n"
        )
        stream.write("\n#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config", type=Path, default=Path("steady_uniform_case_parameters.ini")
    )
    parser.add_argument("--output", type=Path, default=Path("base_state"))
    args = parser.parse_args()

    config_path = args.config.resolve()
    output_dir = args.output.resolve()
    case = base_generator.load_case(config_path)
    settings = parse_benchmark_settings(config_path)

    # A stationary quadtree is intentional for a clean 1-D normal-flow test.
    if not (
        case.min_level == case.initial_level == case.max_level
    ):
        raise ValueError(
            "The relaxation benchmark requires min_level = initial_level = "
            "max_level so the physical mesh remains stationary and uniform"
        )

    base_generator.write_outputs(output_dir, case)

    combined = np.loadtxt(output_dir / "combined_profile.tsv", comments="#")
    z = combined[:, 0]
    write_two_column(output_dir / "gamma.dat", z, combined[:, 7], "gamma")
    write_two_column(output_dir / "viscosity.dat", z, combined[:, 8], "eta")
    write_two_column(output_dir / "traction.dat", z, combined[:, 9], "tau_xz")
    write_benchmark_header(output_dir / "steady_uniform_generated.h", settings)

    shutil.copyfile(config_path, output_dir / "used_steady_uniform_parameters.ini")

    summary_path = output_dir / "steady_uniform_case_summary.txt"
    with summary_path.open("w", encoding="utf-8") as stream:
        stream.write("Steady-uniform relaxation benchmark\n")
        stream.write("===================================\n")
        stream.write(f"configuration              = {config_path.name}\n")
        stream.write(f"initial uniform u_x*       = {settings['initial_uniform_velocity']:.12g}\n")
        stream.write(f"target lower mean u_x*     = 1\n")
        stream.write(f"initial/target mean ratio  = {settings['initial_uniform_velocity']:.12g}\n")
        stream.write(f"comparison output interval = {settings['comparison_output_dt']:.12g}\n")
        stream.write(f"end time                   = {case.end_time:.12g}\n")
        stream.write(f"domain length Lx*          = {case.lx:.12g}\n")
        stream.write(f"total liquid depth         = {case.liquid_depth:.12g}\n")
        stream.write(f"Lx/(H_l+H_u)               = {case.lx/case.liquid_depth:.12g}\n")
        stream.write(f"uniform level              = {case.max_level}\n")
        stream.write(f"Delta*                     = {case.delta_min:.12g}\n")
        stream.write(f"cells through H_l          = {1.0/case.delta_min:.12g}\n")
        stream.write(f"cells through H_u          = {case.depth_ratio/case.delta_min:.12g}\n")
        stream.write(f"stop when converged        = {settings['stop_when_converged']}\n")
        stream.write(f"relative RMS tolerance     = {settings['convergence_relative_rms']:.12g}\n")
        stream.write(f"required consecutive files = {settings['convergence_hold_outputs']}\n")
        stream.write("\nThe target profile is the one-dimensional steady-uniform solution\n")
        stream.write("generated with the complete selected rheology, bounds and air model.\n")

    tracked = [
        output_dir / "velocity.dat",
        output_dir / "pressure.dat",
        output_dir / "gamma.dat",
        output_dir / "viscosity.dat",
        output_dir / "traction.dat",
        output_dir / "combined_profile.tsv",
        output_dir / "base_state_summary.txt",
        output_dir / "steady_uniform_case_summary.txt",
        output_dir / "generated_case.h",
        output_dir / "steady_uniform_generated.h",
        output_dir / "used_case_parameters.ini",
        output_dir / "used_steady_uniform_parameters.ini",
    ]
    with (output_dir / "MANIFEST_STEADY.sha256").open("w", encoding="utf-8") as stream:
        for path in tracked:
            stream.write(f"{sha256(path)}  {path.name}\n")

    print(f"Generated steady-uniform benchmark in: {output_dir}")


if __name__ == "__main__":
    main()
