/**
# Dimensional two-layer power-law roll waves with quadtree AMR

Three physical phases are represented by two nested VOF functions:
`f_lower` (lower liquid) and `f` (total liquid).  This is the AMR branch
of the fixed-grid three-explicit-fraction solver.

By default the case reads two simple, two-column text files generated by
the bundled Python analytical solution.  The default validation setup uses
a passive, low-density/low-viscosity ambient phase, a free-slip embedded
ceiling, a flat internal interface and a small free-surface perturbation.
The base velocity is independent of x, so the initial velocity is
solenoidal.  An optional velocity perturbation is generated from a
streamfunction and is therefore divergence-free as well.
*/

#include "grid/quadtree.h"
#include "adapt_wavelet_leave_interface_limited.h"
#include "embed.h"
#include "navier-stokes/centered.h"
#include "three-phase-stratified-powerlaw.h"
#include "tension.h"
#include "conserving3f-stratified.h"
#include "profile1d.h"
#include "output.h"
#include "gfs_output_safe.h"
#include "navier-stokes/perfs.h"

/* =============================================================================
   USER INPUT PARAMETERS
   =============================================================================
   Edit this section directly before compiling.  No generated C headers are
   used.  Values marked [SYNC] must match the USER INPUT PARAMETERS block in
   generate_base_state.py, because the Python-generated velocity/pressure
   profiles and the Basilisk material model must describe the same case.

   The #ifndef guards let the supplied smoke/regression scripts override a
   small number of run controls without changing this source file. */

/* --- Geometry, gravity and material data [SYNC] --------------------------- */
#ifndef G_ACCEL
# define G_ACCEL 9.81                 /* gravitational acceleration [m/s^2] */
#endif
#ifndef SLOPE_TAN
# define SLOPE_TAN 0.06               /* tan(theta) */
#endif
#ifndef H1
# define H1 0.025                      /* lower-layer normal depth [m] */
#endif
#ifndef H2
# define H2 0.025                      /* upper-layer normal depth [m] */
#endif
#ifndef LX_FACTOR
# define LX_FACTOR 100.0              /* streamwise length divided by H1 */
#endif
#ifndef NOMINAL_HEIGHT
# define NOMINAL_HEIGHT 0.11         /* requested embedded ceiling [m] */
#endif

#ifndef RHOLOWERLAYER
# define RHOLOWERLAYER 1500.0         /* lower-liquid density [kg/m^3] */
#endif
#ifndef RHOUPPERLAYER
# define RHOUPPERLAYER 1200.0         /* upper-liquid density [kg/m^3] */
#endif
#ifndef AIRRHO
# define AIRRHO 10.0                   /* passive ambient density [kg/m^3] */
#endif

#ifndef K_LOWER
# define K_LOWER 6.0                  /* lower consistency [Pa s^n] */
#endif
#ifndef N_LOWER
# define N_LOWER 0.4                  /* lower power-law index */
#endif
#ifndef K_UPPER
# define K_UPPER 3.0                  /* upper consistency [Pa s^n] */
#endif
#ifndef N_UPPER
# define N_UPPER 0.8                  /* upper power-law index */
#endif
#ifndef MUMAXLOWER
# define MUMAXLOWER 28.10              /* lower viscosity cap [Pa s] */
#endif
#ifndef MUMAXUPPER
# define MUMAXUPPER 28.10              /* upper viscosity cap [Pa s] */
#endif
#ifndef AIRMU
# define AIRMU 0.01                 /* passive ambient viscosity [Pa s] */
#endif
#ifndef GAMMA_MIN
# define GAMMA_MIN 1.e-8              /* shear-rate floor [1/s] */
#endif

/* --- Quadtree and time integration --------------------------------------- */
#ifndef MAXLEVEL
# define MAXLEVEL 11                  /* [SYNC] with max_level in Python */
#endif
#ifndef MINLEVEL
# define MINLEVEL 3
#endif
#ifndef INITLEVEL
# define INITLEVEL 10
#endif
#ifndef END_TIME
# define END_TIME 25.
#endif
#ifndef MAX_DT
# define MAX_DT 2.e-3
#endif
#ifndef CFL_NUMBER
# define CFL_NUMBER 0.47
#endif
#ifndef SOLVER_TOLERANCE
# define SOLVER_TOLERANCE 5.5e-4
#endif
#ifndef SOLVER_NITERMAX
# define SOLVER_NITERMAX 256
#endif

/* --- Output intervals ---------------------------------------------------- */
#ifndef OUTPUT_DT
# define OUTPUT_DT 0.25
#endif
#ifndef GFS_DT
# define GFS_DT 0.25
#endif
#ifndef DUMP_DT
# define DUMP_DT 5.0
#endif
#ifndef ENABLE_DUMP_OUTPUT
# define ENABLE_DUMP_OUTPUT 1
#endif
#ifndef WAVE_AMPLITUDE_EVERY
# define WAVE_AMPLITUDE_EVERY 50       /* track amplitudes every 50 steps */
#endif
#ifndef PERTURBATION_MODE_NUMBER
# define PERTURBATION_MODE_NUMBER 1     /* sinusoidal initial mode */
#endif
#ifndef WAVE_MODE_NUMBER
# define WAVE_MODE_NUMBER PERTURBATION_MODE_NUMBER
#endif
#ifndef INITIAL_AUDIT_WARNING_TOL
# define INITIAL_AUDIT_WARNING_TOL 1.e-5 /* scaled divergence warning */
#endif

/* --- Initial sinusoidal disturbance -------------------------------------
   The default test perturbs only the upper-layer thickness by 0.1%.  If the
   velocity amplitude is nonzero, the perturbation is generated from a
   streamfunction rather than by multiplying U by an x-dependent factor. */
#ifndef VELOCITY_PERTURBATION_AMPLITUDE
# define VELOCITY_PERTURBATION_AMPLITUDE 0.
#endif
#ifndef LOWER_DEPTH_PERTURBATION_AMPLITUDE
# define LOWER_DEPTH_PERTURBATION_AMPLITUDE 0.
#endif
#ifndef UPPER_DEPTH_PERTURBATION_AMPLITUDE
# define UPPER_DEPTH_PERTURBATION_AMPLITUDE 0.05
#endif
#ifndef PERTURBATION_PHASE
# define PERTURBATION_PHASE 0.
#endif
/* 1: locally hydrostatic pressure for perturbed interfaces.
   0: use the unperturbed analytical profile p(y). */
#ifndef INITIAL_PRESSURE_MODE
# define INITIAL_PRESSURE_MODE 1
#endif

/* --- AMR controls (dimensional tolerances) ------------------------------- */
#ifndef U_ERR
# define U_ERR 0.5
#endif
#ifndef V_ERR
# define V_ERR 0.25
#endif
#ifndef U_ERRAIR
# define U_ERRAIR 1.
#endif
#ifndef V_ERRAIR
# define V_ERRAIR 1.
#endif
#ifndef OMEGA_ERR
# define OMEGA_ERR 1.0
#endif
#ifndef SHEAR_ERR
# define SHEAR_ERR 2.0
#endif
#ifndef INTERFACE_PADDING
# define INTERFACE_PADDING 1
#endif
#ifndef INTERFACE_EPS
# define INTERFACE_EPS 1.e-6
#endif
#ifndef CEILING_FINE_FRACTION
# define CEILING_FINE_FRACTION 0.975
#endif
#ifndef CEILING_LEVEL_DROP
# define CEILING_LEVEL_DROP 3
#endif
#ifndef INIT_ADAPT_PASSES
# define INIT_ADAPT_PASSES 8
#endif
#ifndef BED_FINE_HEIGHT
/* Keep the complete maximally perturbed lower layer at MAXLEVEL. */
# define BED_FINE_HEIGHT (H1*(1. + fabs(LOWER_DEPTH_PERTURBATION_AMPLITUDE)))
#endif

/* --- Interfacial physics ------------------------------------------------- */
#ifndef SIGMA_INTERNAL
# define SIGMA_INTERNAL 1.e-4         /* lower/upper tension [N/m] */
#endif
#ifndef SIGMA_FREE
# define SIGMA_FREE 1.e-4             /* upper/air tension [N/m] */
#endif
#ifndef AIR_STREAMWISE_GRAVITY
# define AIR_STREAMWISE_GRAVITY 0
#endif

/* --- Plain-text analytical input ---------------------------------------- */
#ifndef BASE_STATE_DIR
# define BASE_STATE_DIR "base_state"
#endif
#ifndef BASE_VELOCITY_FILE
# define BASE_VELOCITY_FILE "velocity.dat"
#endif
#ifndef BASE_PRESSURE_FILE
# define BASE_PRESSURE_FILE "pressure.dat"
#endif

/* =============================================================================
   END USER INPUT PARAMETERS
   ============================================================================= */

#define LIQUID_DEPTH (H1 + H2)
#define LX (LX_FACTOR*H1)
#define SIN_THETA (SLOPE_TAN/sqrt(1. + sq(SLOPE_TAN)))
#define COS_THETA (1./sqrt(1. + sq(SLOPE_TAN)))

face vector gravity_accel[];

Profile1D profile_u0, profile_p;

scalar omega_amr[], shear_amr[];
scalar speed_lower[], speed_upper[], speed_air[];
scalar level_field[];

static double ceiling_y = NOMINAL_HEIGHT;
static double u_reference = 1.;
static int last_nf = 0, last_nc = 0;
static FILE * wave_amplitude_fp = NULL;

u.n[bottom] = dirichlet(0.);
u.t[bottom] = dirichlet(0.);
u.n[top] = dirichlet(0.);
u.t[top] = dirichlet(0.);
uf.n[bottom] = 0.;
uf.n[top] = 0.;

/* Free-slip embedded ceiling, following the demonstrated Basilisk
   component-wise homogeneous-Neumann pattern for embedded boundaries. */
// u.n[embed] = neumann(0.);
// u.t[embed] = neumann(0.);
// The pressure boundary is left to centered.h's acceleration-consistent rule.

static inline double finest_delta (void)
{
  return LX/(double)(1 << MAXLEVEL);
}

static void read_profile_from_dir (Profile1D * p,
                                   const char * directory,
                                   const char * basename)
{
  char path[1024];
  snprintf (path, sizeof(path), "%s/%s", directory, basename);
  profile1d_read (p, path);
  fprintf (ferr, "# read %s: %d values from y=%g to y=%g\n",
           path, p->n, p->x[0], p->x[p->n - 1]);
}

static double expected_interface_velocity (void)
{
  const double gs = G_ACCEL*SIN_THETA;
  const double tau_b = gs*(RHOLOWERLAYER*H1 + RHOUPPERLAYER*H2);
  const double tau_i = RHOUPPERLAYER*gs*H2;
  const double exponent = (N_LOWER + 1.)/N_LOWER;
  const double coefficient = N_LOWER/(N_LOWER + 1.)/
    (RHOLOWERLAYER*gs*pow(K_LOWER, 1./N_LOWER));
  return coefficient*(pow(tau_b, exponent) - pow(tau_i, exponent));
}

static double expected_surface_velocity (void)
{
  const double gs = G_ACCEL*SIN_THETA;
  const double exponent = (N_UPPER + 1.)/N_UPPER;
  const double increment = N_UPPER/(N_UPPER + 1.)*
    pow(RHOUPPERLAYER*gs/K_UPPER, 1./N_UPPER)*pow(H2, exponent);
  return expected_interface_velocity() + increment;
}

static double expected_bed_pressure (void)
{
  const double gn = G_ACCEL*COS_THETA;
  return AIRRHO*gn*(ceiling_y - LIQUID_DEPTH) +
    RHOUPPERLAYER*gn*H2 + RHOLOWERLAYER*gn*H1;
}

static void validate_case_parameters (void)
{
  if (MAXLEVEL < MINLEVEL || INITLEVEL < MINLEVEL || INITLEVEL > MAXLEVEL) {
    fprintf (ferr,
             "Invalid mesh levels: MINLEVEL=%d INITLEVEL=%d MAXLEVEL=%d.\n",
             MINLEVEL, INITLEVEL, MAXLEVEL);
    exit (1);
  }
  if (G_ACCEL <= 0. || SLOPE_TAN <= 0. || H1 <= 0. || H2 <= 0. ||
      LX_FACTOR <= 0. || NOMINAL_HEIGHT <= H1 + H2 ||
      RHOLOWERLAYER <= 0. || RHOUPPERLAYER <= 0. || AIRRHO <= 0. ||
      K_LOWER <= 0. || K_UPPER <= 0. || N_LOWER <= 0. || N_UPPER <= 0. ||
      MUMAXLOWER <= 0. || MUMAXUPPER <= 0. || AIRMU <= 0. ||
      GAMMA_MIN <= 0. || SOLVER_TOLERANCE <= 0. || SOLVER_NITERMAX <= 0 ||
      MAX_DT <= 0. || CFL_NUMBER <= 0.) {
    fprintf (ferr,
             "One or more geometry/material/solver parameters are invalid. "
             "Check the USER INPUT PARAMETERS section.\n");
    exit (1);
  }
  if (WAVE_AMPLITUDE_EVERY <= 0 || WAVE_MODE_NUMBER <= 0 ||
      PERTURBATION_MODE_NUMBER <= 0) {
    fprintf (ferr,
             "Wave-output interval and mode numbers must be positive: "
             "every=%d perturbationMode=%d trackedMode=%d.\n",
             WAVE_AMPLITUDE_EVERY, PERTURBATION_MODE_NUMBER,
             WAVE_MODE_NUMBER);
    exit (1);
  }
  if (fabs(VELOCITY_PERTURBATION_AMPLITUDE) >= 1.) {
    fprintf (ferr,
             "The optional streamfunction velocity amplitude must satisfy "
             "|A_u| < 1.\n");
    exit (1);
  }
}

static void validate_simple_text_profiles (void)
{
  if (profile_u0.n != profile_p.n) {
    fprintf (ferr,
             "Simple profiles have different row counts: velocity=%d "
             "pressure=%d\n",
             profile_u0.n, profile_p.n);
    exit (1);
  }

  const double xtol = 1.e-10*max(1., ceiling_y);
  for (int j = 0; j < profile_u0.n; j++)
    if (fabs(profile_u0.x[j] - profile_p.x[j]) > xtol) {
      fprintf (ferr,
               "Simple profiles use different y coordinates at row %d.\n",
               j + 1);
      exit (1);
    }

  if (fabs(profile_u0.x[0]) > xtol ||
      fabs(profile_u0.x[profile_u0.n - 1] - ceiling_y) > xtol) {
    fprintf (ferr,
             "Profiles must cover y=0 to the compiled ceiling_y=%g; "
             "got [%g,%g].\n"
             "Synchronize generate_base_state.py and roll_wave_amr.c, then "
             "regenerate the base state.\n",
             ceiling_y, profile_u0.x[0], profile_u0.x[profile_u0.n - 1]);
    exit (1);
  }

  const double ubed = profile1d_eval (&profile_u0, 0.);
  const double ui_file = profile1d_eval (&profile_u0, H1);
  const double us_file = profile1d_eval (&profile_u0, LIQUID_DEPTH);
  const double uceil = profile1d_eval (&profile_u0, ceiling_y);
  const double pbed_file = profile1d_eval (&profile_p, 0.);
  const double pceil = profile1d_eval (&profile_p, ceiling_y);
  const double ui_expected = expected_interface_velocity();
  const double us_expected = expected_surface_velocity();
  const double pbed_expected = expected_bed_pressure();

  double air_umin = HUGE, air_umax = -HUGE;
  for (int j = 0; j < profile_u0.n; j++)
    if (profile_u0.x[j] >= LIQUID_DEPTH - xtol) {
      air_umin = min(air_umin, profile_u0.value[j]);
      air_umax = max(air_umax, profile_u0.value[j]);
    }

  const double utol = 2.e-8*max(1., fabs(us_expected));
  const double ptol = 2.e-8*max(1., fabs(pbed_expected));
  if (fabs(ubed) > utol || fabs(uceil - us_expected) > utol ||
      fabs(pceil) > ptol || fabs(ui_file - ui_expected) > utol ||
      fabs(us_file - us_expected) > utol ||
      fabs(pbed_file - pbed_expected) > ptol ||
      air_umax - air_umin > utol) {
    fprintf (ferr,
             "Analytical profile is not the compatible passive-ambient "
             "base state.\n"
             "  interface velocity: file=%g expected=%g\n"
             "  surface velocity:   file=%g expected=%g\n"
             "  ceiling velocity:   file=%g expected=%g\n"
             "  ambient spread:     %g\n"
             "  bed pressure:       file=%g expected=%g\n"
             "  bed velocity / ceiling pressure: %g / %g\n",
             ui_file, ui_expected, us_file, us_expected,
             uceil, us_expected, air_umax - air_umin,
             pbed_file, pbed_expected, ubed, pceil);
    exit (1);
  }

  u_reference = us_file;
  fprintf (ferr,
           "# compatible base state validated: U_interface=%g U_surface=%g "
           "U_ambient=%g p_bed=%g ceiling=%g\n",
           ui_file, us_file, uceil, pbed_file, ceiling_y);
}

/** Periodic disturbance shared by the depth and velocity perturbations. */
static inline double disturbance_sine (double xx)
{
  return sin(2.*pi*PERTURBATION_MODE_NUMBER*xx/LX +
             PERTURBATION_PHASE);
}

static inline double initial_lower_depth (double xx)
{
  return H1*(1. + LOWER_DEPTH_PERTURBATION_AMPLITUDE*
                    disturbance_sine(xx));
}

static inline double initial_upper_depth (double xx)
{
  return H2*(1. + UPPER_DEPTH_PERTURBATION_AMPLITUDE*
                    disturbance_sine(xx));
}

static inline double initial_internal_interface (double xx)
{
  return initial_lower_depth(xx);
}

static inline double initial_free_surface (double xx)
{
  return initial_lower_depth(xx) + initial_upper_depth(xx);
}

/** Compatible base velocity plus an optional divergence-free perturbation.
    The perturbation comes from

      psi' = A Uref yc/(2 pi) [1 - cos(2 pi y/yc)] sin(kx + phi),

    with u'_x = d psi'/dy and u'_y = -d psi'/dx.  It vanishes at the bed
    and ceiling and causes no sinusoidal variation of total discharge. */
static inline void initial_velocity_components (double xx, double yy,
                                                double * ux, double * uy)
{
  const double mode = PERTURBATION_MODE_NUMBER;
  const double phase = 2.*pi*mode*xx/LX + PERTURBATION_PHASE;
  const double sy = clamp(yy/(ceiling_y + SEPS), 0., 1.);
  const double amp = VELOCITY_PERTURBATION_AMPLITUDE*u_reference;

  /* psi' = A Uref yc/(2 pi) [1 - cos(2 pi y/yc)] sin(kx + phi).
     This gives zero normal velocity at y=0 and y=yc, zero modal total
     discharge, and exactly divergence-free analytical perturbations. */
  *ux = profile1d_eval(&profile_u0, yy) +
    amp*sin(2.*pi*sy)*sin(phase);
  *uy = -amp*mode*(ceiling_y/LX)*
    (1. - cos(2.*pi*sy))*cos(phase);
}

/** Piecewise hydrostatic pressure for the locally perturbed interfaces,
    with p=0 at the embedded ceiling. */
static inline double local_hydrostatic_pressure (double xx, double yy)
{
  const double h1x = initial_lower_depth(xx);
  const double h2x = initial_upper_depth(xx);
  const double eta2 = h1x + h2x;
  const double gn = G_ACCEL*COS_THETA;

  if (yy > eta2)
    return AIRRHO*gn*(ceiling_y - yy);
  if (yy > h1x)
    return AIRRHO*gn*(ceiling_y - eta2) +
      RHOUPPERLAYER*gn*(eta2 - yy);
  return AIRRHO*gn*(ceiling_y - eta2) +
    RHOUPPERLAYER*gn*h2x + RHOLOWERLAYER*gn*(h1x - yy);
}

static inline void build_embedded_ceiling (void)
{
  solid (cs, fs, ceiling_y - y);
  fractions_cleanup (cs, fs);
}

/** Maximum level allowed by position.  The wavelet criterion can coarsen
    the interior, while mixed f_lower, f and cs cells are protected by the
    custom adaptation function. */
static int local_maxlevel_cell (double xx, double yy, double zz,
                                double delta)
{
  (void) xx; (void) zz;
  /* Apply the requested y <= 0.975*ceiling rule to the complete cell
     footprint, not only its centre.  This prevents a coarse cut cell whose
     centre lies just below the threshold from being refined back to
     MAXLEVEL merely to represent the horizontal ceiling. */
  if (yy + 0.5*delta <= ceiling_y*CEILING_FINE_FRACTION)
    return MAXLEVEL;
  return max(MINLEVEL, MAXLEVEL - CEILING_LEVEL_DROP);
}

static int local_minlevel (double xx, double yy, double zz)
{
  (void) xx; (void) zz;
  const double dmin = finest_delta();
  if (yy <= BED_FINE_HEIGHT + 1.5*dmin)
    return MAXLEVEL;
  return MINLEVEL;
}

static inline void force_required_refinement (void)
{
  const double dmin = finest_delta();
  const double ceiling_limit = ceiling_y*CEILING_FINE_FRACTION;

  /* Resolve the lower liquid/basal high-shear region at the finest level. */
  refine (y <= 4.5*dmin  && level < MAXLEVEL);
}

static void validate_initialization_parameters (void)
{
  if (fabs(LOWER_DEPTH_PERTURBATION_AMPLITUDE) >= 1. ||
      fabs(UPPER_DEPTH_PERTURBATION_AMPLITUDE) >= 1.) {
    fprintf (ferr,
             "Depth-perturbation amplitudes must have absolute value < 1.\n");
    exit (1);
  }
  const double max_surface =
    H1*(1. + fabs(LOWER_DEPTH_PERTURBATION_AMPLITUDE)) +
    H2*(1. + fabs(UPPER_DEPTH_PERTURBATION_AMPLITUDE));
  if (max_surface >= ceiling_y*CEILING_FINE_FRACTION) {
    fprintf (ferr,
             "The maximum initial free surface (%g) reaches the ceiling "
             "coarsening band (%g). Reduce depth amplitude or raise the "
             "ceiling.\n",
             max_surface, ceiling_y*CEILING_FINE_FRACTION);
    exit (1);
  }
  if (max(fabs(LOWER_DEPTH_PERTURBATION_AMPLITUDE),
          fabs(UPPER_DEPTH_PERTURBATION_AMPLITUDE)) > 0.02)
    fprintf (ferr,
             "WARNING: depth perturbation exceeds 2%%; this is not a linear "
             "stability initialization.\n");
}

static void set_initial_fields (void)
{
  /* Both cumulative VOF fields receive the sinusoidal depth disturbance. */
  fraction (f_lower, initial_internal_interface(x) - y);
  fraction (f, initial_free_surface(x) - y);

  foreach() {
    initial_velocity_components (x, y, &u.x[], &u.y[]);
#if INITIAL_PRESSURE_MODE == 1
    p[] = local_hydrostatic_pressure(x, y);
#else
    p[] = profile1d_eval(&profile_p, y);
#endif
  }

  stratified_enforce_hierarchy();
  boundary ((scalar *){u, p});
}

static void update_amr_indicators (void)
{
  boundary ((scalar *){u});
  vorticity (u, omega_amr);
  foreach() {
    const double dudx = (u.x[1,0] - u.x[-1,0])/(2.*Delta);
    const double dudy = (u.x[0,1] - u.x[0,-1])/(2.*Delta);
    const double dvdx = (u.y[1,0] - u.y[-1,0])/(2.*Delta);
    const double dvdy = (u.y[0,1] - u.y[0,-1])/(2.*Delta);
    shear_amr[] = sqrt(max(0., 2.*(sq(dudx) + sq(dvdy)) +
                                  sq(dudy + dvdx)));
    const double speed = sqrt(sq(u.x[]) + sq(u.y[]));
    double a1, a2, a3;
    stratified_phase_values (f_lower[], f[], &a1, &a2, &a3);
    speed_lower[] = a1*speed;
    speed_upper[] = a2*speed;
    speed_air[] = a3*speed;
    level_field[] = level;
  }
  boundary ({omega_amr, shear_amr, speed_lower, speed_upper,
             speed_air, level_field});
}

static astats perform_adaptation (void)
{
  update_amr_indicators();
  Adapt_limited controls = {
    .slist = (scalar *){omega_amr, speed_lower, speed_upper, speed_air},
    .vol_frac = (scalar *){f_lower, f, cs},
    .max = (double []){OMEGA_ERR, U_ERR, U_ERR, U_ERRAIR},
    .MLFun = NULL,
    .MLFunDelta = local_maxlevel_cell,
    .MinFun = local_minlevel,
    .minlevel = MINLEVEL,
    .padding = INTERFACE_PADDING,
    .interface_eps = INTERFACE_EPS,
    .list = all
  };
  astats st = adapt_wavelet_limited (controls);

  build_embedded_ceiling();
  stratified_enforce_hierarchy();
  last_nf = st.nf;
  last_nc = st.nc;
  return st;
}

typedef struct {
  double mean_internal, mean_free, mean_upper;
  double cos_internal, sin_internal, amplitude_internal;
  double cos_free, sin_free, amplitude_free;
  double cos_upper, sin_upper, amplitude_upper;
} WaveMetrics;

/** Fourier amplitudes from conservative VOF volume integrals. */
static WaveMetrics compute_wave_metrics (void)
{
  const double k = 2.*pi*WAVE_MODE_NUMBER/LX;
  double vl = 0., vf = 0.;
  double cl = 0., sl = 0., cf = 0., sf = 0.;
  foreach (reduction(+:vl) reduction(+:vf)
           reduction(+:cl) reduction(+:sl)
           reduction(+:cf) reduction(+:sf)) {
    const double vol = dv();
    const double c = cos(k*x), ss = sin(k*x);
    vl += f_lower[]*vol;
    vf += f[]*vol;
    cl += f_lower[]*c*vol;
    sl += f_lower[]*ss*vol;
    cf += f[]*c*vol;
    sf += f[]*ss*vol;
  }
  const double fac = 2./LX;
  WaveMetrics w = {0};
  w.mean_internal = vl/LX;
  w.mean_free = vf/LX;
  w.mean_upper = (vf - vl)/LX;
  w.cos_internal = fac*cl;
  w.sin_internal = fac*sl;
  w.cos_free = fac*cf;
  w.sin_free = fac*sf;
  w.cos_upper = w.cos_free - w.cos_internal;
  w.sin_upper = w.sin_free - w.sin_internal;
  w.amplitude_internal = hypot(w.cos_internal, w.sin_internal);
  w.amplitude_free = hypot(w.cos_free, w.sin_free);
  w.amplitude_upper = hypot(w.cos_upper, w.sin_upper);
  return w;
}

/** Audit the initial divergence and streamwise discharge mode. */
static void write_initial_condition_audit (void)
{
  boundary ((scalar *){u});
  const double k = 2.*pi*WAVE_MODE_NUMBER/LX;
  double divmax = 0., div2 = 0., volume = 0.;
  double qcos = 0., qsin = 0.;
  foreach (reduction(max:divmax) reduction(+:div2) reduction(+:volume)
           reduction(+:qcos) reduction(+:qsin)) {
    const double vol = dv();
    qcos += u.x[]*cos(k*x)*vol;
    qsin += u.x[]*sin(k*x)*vol;
    if (cs[] > 1. - 1.e-10 && y > 1.5*Delta &&
        y < ceiling_y - 1.5*Delta) {
      const double divu =
        (u.x[1,0] - u.x[-1,0] + u.y[0,1] - u.y[0,-1])/(2.*Delta);
      divmax = max(divmax, fabs(divu));
      div2 += sq(divu)*vol;
      volume += vol;
    }
  }
  qcos *= 2./LX;
  qsin *= 2./LX;
  const double divrms = sqrt(div2/(volume + SEPS));
  const double divscale = max(u_reference/H1, SEPS);
  const WaveMetrics w = compute_wave_metrics();

  if (pid() == 0) {
    FILE * fp = fopen ("initial_condition_audit.tsv", "w");
    if (!fp) {
      perror("initial_condition_audit.tsv");
      exit (1);
    }
    fprintf (fp,
             "divMax[1/s]\tdivRMS[1/s]\tdivMaxScaled\tQcos[m2/s]"
             "\tQsin[m2/s]\tAinternal[m]\tAfree[m]\tAupper[m]\n");
    fprintf (fp, "%.16e\t%.16e\t%.16e\t%.16e\t%.16e\t%.16e\t%.16e\t%.16e\n",
             divmax, divrms, divmax/divscale, qcos, qsin,
             w.amplitude_internal, w.amplitude_free, w.amplitude_upper);
    fclose (fp);
  }
  fprintf (ferr,
           "# initial audit: divMax=%g divRMS=%g scaledDivMax=%g "
           "Qmode=(%g,%g) Ainternal=%g Afree=%g Aupper=%g\n",
           divmax, divrms, divmax/divscale, qcos, qsin,
           w.amplitude_internal, w.amplitude_free, w.amplitude_upper);
  if (divmax/divscale > INITIAL_AUDIT_WARNING_TOL)
    fprintf (ferr,
             "WARNING: initialized velocity divergence exceeds scaled tolerance %g.\n",
             (double)INITIAL_AUDIT_WARNING_TOL);
}

int main (void)
{
  validate_case_parameters();
  size (LX);
  origin (0., 0.);
  periodic (right);

  /* Align the embedded ceiling with a MAXLEVEL cell face, avoiding a row
     of arbitrarily small cut cells. */
  const double dmin = finest_delta();
  ceiling_y = ceil(NOMINAL_HEIGHT/dmin - 1.e-12)*dmin;

  rho1 = RHOLOWERLAYER;
  rho2 = RHOUPPERLAYER;
  rho3 = AIRRHO;

  rheology1 = (StratifiedRheology) {
    .K = K_LOWER, .n = N_LOWER, .tau0 = 0., .m = 0.,
    .mu_min = 0., .mu_max = MUMAXLOWER, .gamma_min = GAMMA_MIN,
    .regularized = 0
  };
  rheology2 = (StratifiedRheology) {
    .K = K_UPPER, .n = N_UPPER, .tau0 = 0., .m = 0.,
    .mu_min = 0., .mu_max = MUMAXUPPER, .gamma_min = GAMMA_MIN,
    .regularized = 0
  };
  rheology3 = (StratifiedRheology) {
    .K = AIRMU, .n = 1., .tau0 = 0., .m = 0.,
    .mu_min = AIRMU, .mu_max = AIRMU, .gamma_min = 1.e-12,
    .regularized = 0
  };

  f_lower.sigma = SIGMA_INTERNAL;
  f.sigma = SIGMA_FREE;

  a = gravity_accel;
  CFL = CFL_NUMBER;
//   DT = MAX_DT;
  TOLERANCE = SOLVER_TOLERANCE;
  NITERMAX = SOLVER_NITERMAX;

  init_grid (1 << INITLEVEL);
  run();
}

event init (i = 0)
{
  if (pid() == 0)
    system ("mkdir -p gfs dumps interfaces slices");
#if _MPI
  MPI_Barrier (MPI_COMM_WORLD);
#endif

  read_profile_from_dir (&profile_u0, BASE_STATE_DIR, BASE_VELOCITY_FILE);
  read_profile_from_dir (&profile_p, BASE_STATE_DIR, BASE_PRESSURE_FILE);
  validate_simple_text_profiles();

  build_embedded_ceiling();
  validate_initialization_parameters();
  force_required_refinement();
  build_embedded_ceiling();

  for (int pass = 0; pass < INIT_ADAPT_PASSES; pass++) {
    set_initial_fields();
    astats st = perform_adaptation();
    fprintf (ferr, "# init AMR pass %d: nf=%d nc=%d cells=%ld\n",
             pass + 1, st.nf, st.nc, grid->tn);
    if (st.nf == 0 && st.nc == 0)
      break;
  }
  set_initial_fields();
  update_amr_indicators();
  write_initial_condition_audit();

  const double we_free = SIGMA_FREE > 0. ?
    rho2*sq(u_reference)*H2/SIGMA_FREE : HUGE;
  const double we_internal = SIGMA_INTERNAL > 0. ?
    rho1*sq(u_reference)*H1/SIGMA_INTERNAL : HUGE;

  fprintf (ferr,
           "# AMR roll wave: Lx=%g nominalHeight=%g embeddedCeiling=%g "
           "dmin=%g MAXLEVEL=%d MINLEVEL=%d activeCells=%ld\n",
           LX, (double)NOMINAL_HEIGHT, ceiling_y, finest_delta(),
           MAXLEVEL, MINLEVEL, grid->tn);
  fprintf (ferr,
           "# AMR policy: full MAXLEVEL below y=%g; ceiling band max=%d; "
           "bed fine height=%g\n",
           ceiling_y*CEILING_FINE_FRACTION,
           max(MINLEVEL, MAXLEVEL - CEILING_LEVEL_DROP),
           (double)BED_FINE_HEIGHT);
  fprintf (ferr,
           "# cells through H1=%g; sigma12=%g sigma23=%g "
           "We12=%g We23=%g velocityAmp=%g lowerDepthAmp=%g "
           "upperDepthAmp=%g perturbationMode=%d trackedMode=%d "
           "amplitudeEvery=%d\n",
           H1/finest_delta(), (double)SIGMA_INTERNAL, (double)SIGMA_FREE,
           we_internal, we_free,
           (double)VELOCITY_PERTURBATION_AMPLITUDE,
           (double)LOWER_DEPTH_PERTURBATION_AMPLITUDE,
           (double)UPPER_DEPTH_PERTURBATION_AMPLITUDE,
           PERTURBATION_MODE_NUMBER, WAVE_MODE_NUMBER,
           WAVE_AMPLITUDE_EVERY);
  fprintf (ferr,
           "# columns: i t dt leaves minLevel maxLevel lowerMin interfaceMin "
           "ceilingMax mgp mgu pRes uRes "
           "V1 V2 V3 Px KE Umax hierarchy bounds dVlower dVliquid corrected "
           "nf nc\n");
}

event acceleration (i++)
{
  face vector av = a;
  const double gs = G_ACCEL*SIN_THETA;
  const double gn = G_ACCEL*COS_THETA;

  foreach_face(x) {
    const double lower = (f_lower[] + f_lower[-1])/2.;
    const double liquid = (f[] + f[-1])/2.;
    double a1, a2, a3;
    stratified_phase_values (lower, liquid, &a1, &a2, &a3);
    const double rhof = a1*rho1 + a2*rho2 + a3*rho3;
#if AIR_STREAMWISE_GRAVITY
    av.x[] += gs;
#else
    av.x[] += gs*(a1*rho1 + a2*rho2)/rhof;
#endif
  }
  foreach_face(y)
    av.y[] -= gn;
}

event adapt (i++)
{
  perform_adaptation();
}

event wave_amplitude (i = 0; i += WAVE_AMPLITUDE_EVERY)
{
  const WaveMetrics w = compute_wave_metrics();
  if (pid() == 0) {
    static double previous_t = -1.;
    static double previous_internal = 0., previous_free = 0., previous_upper = 0.;
    if (!wave_amplitude_fp) {
      wave_amplitude_fp = fopen ("wave_amplitude.tsv", "w");
      if (!wave_amplitude_fp) {
        perror("wave_amplitude.tsv");
        exit (1);
      }
      fprintf (wave_amplitude_fp,
               "i\tt[s]\tdt[s]\tmode\tmeanInternal[m]\tmeanFree[m]"
               "\tmeanUpper[m]\tcosInternal[m]\tsinInternal[m]"
               "\tAinternal[m]\tAinternal/H1\tcosFree[m]\tsinFree[m]"
               "\tAfree[m]\tAfree/(H1+H2)\tcosUpper[m]\tsinUpper[m]"
               "\tAupper[m]\tAupper/H2\tsigmaInternal[1/s]"
               "\tsigmaFree[1/s]\tsigmaUpper[1/s]\n");
    }
    double sigma_internal = NAN, sigma_free = NAN, sigma_upper = NAN;
    if (previous_t >= 0. && t > previous_t) {
      if (previous_internal > 0. && w.amplitude_internal > 0.)
        sigma_internal = log(w.amplitude_internal/previous_internal)/(t - previous_t);
      if (previous_free > 0. && w.amplitude_free > 0.)
        sigma_free = log(w.amplitude_free/previous_free)/(t - previous_t);
      if (previous_upper > 0. && w.amplitude_upper > 0.)
        sigma_upper = log(w.amplitude_upper/previous_upper)/(t - previous_t);
    }
    fprintf (wave_amplitude_fp,
             "%d\t%.16e\t%.16e\t%d\t%.16e\t%.16e\t%.16e"
             "\t%.16e\t%.16e\t%.16e\t%.16e"
             "\t%.16e\t%.16e\t%.16e\t%.16e"
             "\t%.16e\t%.16e\t%.16e\t%.16e"
             "\t%.16e\t%.16e\t%.16e\n",
             i, t, dt, WAVE_MODE_NUMBER,
             w.mean_internal, w.mean_free, w.mean_upper,
             w.cos_internal, w.sin_internal, w.amplitude_internal,
             w.amplitude_internal/H1,
             w.cos_free, w.sin_free, w.amplitude_free,
             w.amplitude_free/LIQUID_DEPTH,
             w.cos_upper, w.sin_upper, w.amplitude_upper,
             w.amplitude_upper/H2,
             sigma_internal, sigma_free, sigma_upper);
    fflush (wave_amplitude_fp);
    previous_t = t;
    previous_internal = w.amplitude_internal;
    previous_free = w.amplitude_free;
    previous_upper = w.amplitude_upper;
  }
}

event diagnostics (i += 10)
{
  stratified_update_phase_fields();
  long leaves = 0;
  int levmin = MAXLEVEL, levmax = 0;
  int lower_min_level = MAXLEVEL, interface_min_level = MAXLEVEL;
  int ceiling_max_level = 0;
  double v1 = 0., v2 = 0., v3 = 0., px = 0., ke = 0., umax = 0.;
  foreach (reduction(+:leaves) reduction(min:levmin) reduction(max:levmax)
           reduction(min:lower_min_level) reduction(min:interface_min_level)
           reduction(max:ceiling_max_level)
           reduction(+:v1) reduction(+:v2) reduction(+:v3)
           reduction(+:px) reduction(+:ke) reduction(max:umax)) {
    leaves++;
    levmin = min(levmin, level);
    levmax = max(levmax, level);
    if (y <= BED_FINE_HEIGHT)
      lower_min_level = min(lower_min_level, level);
    if ((f_lower[] > INTERFACE_EPS && f_lower[] < 1. - INTERFACE_EPS) ||
        (f[] > INTERFACE_EPS && f[] < 1. - INTERFACE_EPS))
      interface_min_level = min(interface_min_level, level);
    if (y + 0.5*Delta > ceiling_y*CEILING_FINE_FRACTION &&
        cs[] > INTERFACE_EPS)
      ceiling_max_level = max(ceiling_max_level, level);
    const double vol = dv();
    const double rhoc = stratified_density_cell(f_lower[], f[]);
    v1 += f1[]*vol;
    v2 += f2[]*vol;
    v3 += f3[]*vol;
    px += rhoc*u.x[]*vol;
    ke += 0.5*rhoc*(sq(u.x[]) + sq(u.y[]))*vol;
    umax = max(umax, sqrt(sq(u.x[]) + sq(u.y[])));
  }

  fprintf (ferr,
           "%d %.12g %.12g %ld %d %d %d %d %d %d %d %.3e %.3e "
           "%.10e %.10e %.10e %.10e %.10e %.8e %.3e %.3e "
           "%.3e %.3e %ld %d %d\n",
           i, t, dt, leaves, levmin, levmax,
           lower_min_level, interface_min_level, ceiling_max_level,
           mgp.i, mgu.i, mgp.resa, mgu.resa, v1, v2, v3, px, ke, umax,
           stratified_hierarchy_max, stratified_bound_max,
           stratified_volume_correction_lower,
           stratified_volume_correction_liquid,
           stratified_corrected_cells, last_nf, last_nc);
}

static void write_vertical_slice (const char * name, double xx)
{
  FILE * fp = fopen (name, "w");
  if (!fp) {
    perror(name);
    exit (1);
  }
  fprintf (fp,
           "y\tfLower\tfLiquid\tf1\tf2\tf3\tu\tv\tp\tgammaDot\tmuMix\trho\tlevel\tcs\n");
  const double ds = finest_delta();
  for (double yy = ds/2.; yy < ceiling_y - ds/4.; yy += ds)
    fprintf (fp,
             "%.12e\t%.12e\t%.12e\t%.12e\t%.12e\t%.12e\t"
             "%.12e\t%.12e\t%.12e\t%.12e\t%.12e\t%.12e\t%.12e\t%.12e\n",
             yy, interpolate(f_lower, xx, yy), interpolate(f, xx, yy),
             interpolate(f1, xx, yy), interpolate(f2, xx, yy),
             interpolate(f3, xx, yy), interpolate(u.x, xx, yy),
             interpolate(u.y, xx, yy), interpolate(p, xx, yy),
             interpolate(gammaDot, xx, yy), interpolate(muMix, xx, yy),
             interpolate(rhov, xx, yy), interpolate(level_field, xx, yy),
             interpolate(cs, xx, yy));
  fclose (fp);
}

static void write_interface_facets (scalar c, const char * stem,
                                    double time)
{
  char local[256];
  snprintf (local, sizeof(local), "interfaces/%s-p%05d.dat", stem, pid());
  FILE * fp = fopen (local, "w");
  output_facets (c, fp);
  fclose (fp);
#if _MPI
  MPI_Barrier (MPI_COMM_WORLD);
#endif

  if (pid() == 0) {
    char command[1024];
    snprintf (command, sizeof(command),
              "LC_ALL=C cat interfaces/%s-p*.dat > "
              "interfaces/%s-t%g.dat; rm -f interfaces/%s-p*.dat",
              stem, stem, time, stem);
    system (command);
  }
#if _MPI
  MPI_Barrier (MPI_COMM_WORLD);
#endif
}

event field_outputs (t = 0.; t += OUTPUT_DT; t <= END_TIME + 1.e-12)
{
  stratified_update_phase_fields();
  update_amr_indicators();
  char name[256];
  snprintf (name, sizeof(name), "slices/x0-t%g.tsv", t);
  write_vertical_slice (name, 0.);
  snprintf (name, sizeof(name), "slices/xquarter-t%g.tsv", t);
  write_vertical_slice (name, LX/4.);
  write_interface_facets (f_lower, "internal", t);
  write_interface_facets (f, "free", t);
}

event output_gfs_files (t = 0.; t += GFS_DT; t <= END_TIME + 1.e-12)
{
  stratified_update_phase_fields();
  update_amr_indicators();
  char name[128];
  snprintf (name, sizeof(name), "out-%g.gfs", t);

  /* Keep `f` in the output list because Basilisk output_gfs() declares
     `VariableTracerVOF f` unconditionally.  f_lower exposes the internal
     liquid--liquid interface to GfsView. */
  scalar * gfs_fields = {f, f_lower, f1, f2, f3, cs,
                         u.x, u.y, p, gammaDot, muMix, rhov,
                         omega_amr, shear_amr, level_field};
  output_gfs_safe (name, gfs_fields, true);
}

#if ENABLE_DUMP_OUTPUT
event snapshots (t = 0.; t += DUMP_DT; t <= END_TIME + 1.e-12)
{
  char name[256];
  snprintf (name, sizeof(name), "dumps/dump-%010.5f", t);
  dump (file = name);
}
#endif

event stop (t = END_TIME)
{
  if (wave_amplitude_fp) {
    fclose (wave_amplitude_fp);
    wave_amplitude_fp = NULL;
  }
  profile1d_free (&profile_u0);
  profile1d_free (&profile_p);
  return 1;
}
